#!/usr/bin/env python3
"""
Regenerate src/manifest.js from the contents of questions/.

The manifest is bundled into the Worker (see src/worker.js) and never
served as a static asset, so the master list of sets and their codes
is not directly fetchable by clients.

Conventions
-----------
- Subdirectories under questions/ become codes. A file at
      questions/contracts/graves-mc.json
  gets code "contracts".
- Files placed directly under questions/ (no subdirectory) have no
  code, so they will not be loadable via code entry on the site. They
  can still be loaded via the file-upload zone.
- Only the FIRST-level subdirectory becomes the code. Deeper nesting
  is treated as file organization within a category:
      questions/contracts/week1/foo.json  ->  code "contracts"
- Optional overrides (only for JSON wrapper-format files):
  If a JSON file is an object (not a bare array), it may include any of:
      "_code"  : "tag"             single code, overrides directory
      "_codes" : ["tag1", "tag2"]  multiple codes, overrides directory
      "_name"  : "Display Name"    overrides the auto-derived name
  These keys are harmless to the runtime parser, which ignores them.

Output
------
Writes src/manifest.js as an ES module exporting the manifest array. If
no questions/ directory exists, writes an empty manifest (useful for
testing the public scaffold without adding content).

Usage
-----
    python3 build-manifest.py
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent
QUESTIONS_DIR = ROOT / "questions"
MANIFEST_PATH = ROOT / "src" / "manifest.js"


def pretty_name(filename: str) -> str:
    """Convert a filename like 'graves-mc.json' to 'Graves Mc'."""
    stem = Path(filename).stem
    return stem.replace("-", " ").replace("_", " ").title()


def read_overrides(json_path: Path):
    """Return (codes_override, name_override) from a JSON file's wrapper
    metadata, or (None, None) if not applicable."""
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return None, None

    if not isinstance(data, dict):
        return None, None

    codes = None
    if isinstance(data.get("_codes"), list):
        codes = [str(c).strip() for c in data["_codes"] if str(c).strip()]
    elif isinstance(data.get("_code"), str) and data["_code"].strip():
        codes = [data["_code"].strip()]

    name = None
    if isinstance(data.get("_name"), str) and data["_name"].strip():
        name = data["_name"].strip()

    return codes, name


def collect_sets():
    """Walk questions/ and return a list of manifest entries.
    Returns ([], 0) if questions/ doesn't exist."""
    if not QUESTIONS_DIR.is_dir():
        print(
            f"warning: {QUESTIONS_DIR} does not exist — writing empty manifest",
            file=sys.stderr,
        )
        return [], 0

    sets = []
    skipped = 0

    for path in sorted(QUESTIONS_DIR.rglob("*.json")):
        if not path.is_file():
            continue

        # Verify the file is valid JSON before adding it
        try:
            with open(path, "r", encoding="utf-8") as f:
                json.load(f)
        except json.JSONDecodeError as e:
            rel = path.relative_to(QUESTIONS_DIR).as_posix()
            print(
                f"warning: skipping {rel} - invalid JSON ({e})",
                file=sys.stderr,
            )
            skipped += 1
            continue

        rel_path = path.relative_to(QUESTIONS_DIR).as_posix()
        parts = path.relative_to(QUESTIONS_DIR).parts

        # First-level subdirectory becomes the derived code (if any)
        derived_codes = [parts[0]] if len(parts) > 1 else []

        # In-file overrides (wrapper-format JSON only)
        override_codes, override_name = read_overrides(path)
        codes = override_codes if override_codes is not None else derived_codes
        name = override_name or pretty_name(path.name)

        entry = {"file": rel_path, "name": name}
        if codes:
            if len(codes) == 1:
                entry["code"] = codes[0]
            else:
                entry["codes"] = codes
        sets.append(entry)

    return sets, skipped


def main() -> int:
    sets, skipped = collect_sets()

    # Ensure src/ exists before writing
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)

    body = json.dumps(sets, indent=2, ensure_ascii=False)
    contents = (
        "// Auto-generated by build-manifest.py — do not edit by hand.\n"
        f"export const manifest = {body};\n"
    )
    MANIFEST_PATH.write_text(contents, encoding="utf-8")

    coded = sum(1 for s in sets if "code" in s or "codes" in s)
    uncoded = len(sets) - coded
    print(f"wrote {MANIFEST_PATH}")
    print(
        f"  {len(sets)} set{'s' if len(sets) != 1 else ''} "
        f"({coded} with code, {uncoded} without)"
    )
    if skipped:
        print(f"  {skipped} skipped due to JSON errors")
    return 0


if __name__ == "__main__":
    sys.exit(main())
